### PR TITLE
Initial PR

### PR DESCRIPTION
**Pull request by witekest**
https://github.com/elastic/logstash/issues/5195

### CODE REVIEW

**Comment by witekest** [comment]
The PR contains the commits from our existing repo. We would be very grateful for the reviews.

**Comment by tsvenkat** [comment]
This is a great and useful plugin. Would love to see this merged!

**Comment by Kuckkuck** [comment]
+1

**Comment by majewsky** [comment]
I submitted a [pull request](https://github.com/FujitsuEnablingSoftwareTechnologyGmbH/logstash-output-monasca_log_api/pull/2) on the other repo to introduce distinct `user_domain_name` and `project_domain_name` parameters. Since this changes the configuration parameters, it would be nice to have this merged over there before this PR is merged here.

**Comment by roland-hochmuth** [comment]
Thanks witekest for adding this plugin. This will be a really nice plugin to get added for cross project inter-operability between the Monasca project and Logstash.

**Pull request merged**
